language: python
services:
  - redis-server

python:
  - "3.6"

install:
  - pip install -U pip pipenv virtualenv
  - pipenv install

before_script:
  - . ./local.sh && OUTPUT_DIR=./secrets pipenv run python generate_funding_address.py

script:
  - make test

after_success:
  - pipenv run codecov

branches:
  only:
    - master

deploy:
  provider: script
  script: echo "pushing docker image" # && docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" && make build-image push-image
  on:
    branch: master
